Fix "WARNING: NoClassDefFoundError" when using graphql-java-tools with Spring Boot.
All 'graphql-java' libs appear to have moved to a different groupId: 'com.graphql-java-kickstart'.
We should use that instead.

cf. https://github.com/graphql-java-kickstart/graphql-java-tools#warning-noclassdeffounderror-when-using-spring-boot